development:
  adapter: postgresql
  database: swag3_development
  encoding: unicode
  user: swag3
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: swag3_test
  encoding: unicode
  user: swag3
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: swag3_production
  encoding: unicode
  pool: 5
  timeout: 5000